### ISSUE TITLE
`FileNotFoundError` when using conda installed B-Tax

### ISSUE THREAD

**Issue by hdoupe** [PSLmodels/B-Tax#231]
I got a `FileNotFoundError` when updating B-Tax to 0.2.6 on PolicyBrain. Here's a reproducible example:

```python
from btax.front_end_util import runner_json_tables

inputs = {'start_year': 2018}

result = runner_json_tables(inputs)
```

```
(pb_env) HDoupe-MacBook-Pro:PolicyBrain henrydoupe$ python btax_test.py 
/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/pandas/util/_decorators.py:178: FutureWarning: the 'skip_footer' keyword is deprecated, use 'skipfooter' instead
  return func(*args, **kwargs)
Traceback (most recent call last):
  File "btax_test.py", line 5, in <module>
    result = runner_json_tables(inputs)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/btax/front_end_util.py", line 172, in runner_json_tables
    out = runner(test_run, start_year, iit_reform, **user_params)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/btax/execute.py", line 48, in runner
    run_btax(test_run, True, start_year, {}, **econ_params)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/btax/run_btax.py", line 77, in run_btax
    soi_data = pull_soi_data()
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/btax/soi_processing.py", line 32, in pull_soi_data
    entity_dfs.update(prt.load_partner_data(entity_dfs))
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/btax/pull_soi_partner.py", line 80, in load_partner_data
    skip_footer=6))
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/pandas/util/_decorators.py", line 178, in wrapper
    return func(*args, **kwargs)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/pandas/util/_decorators.py", line 178, in wrapper
    return func(*args, **kwargs)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/pandas/io/excel.py", line 307, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/pandas/io/excel.py", line 394, in __init__
    self.book = xlrd.open_workbook(self._io)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/xlrd/__init__.py", line 111, in open_workbook
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/btax/data/raw_data/soi/soi_partner/13pa03.xls'
```

This file [exists in the B-Tax repo][1] but it is not included with the conda installed version of B-Tax:

```bash
(pb_env) HDoupe-MacBook-Pro:PolicyBrain henrydoupe$ ls ~/anaconda3/envs/pb_env/lib/python3.6/site-packages/btax/data/raw_data/soi/soi_partner/
13pa05_Crosswalk.csv				partner_crosswalk_detailed_industries.csv
```

It looks like the [`soi_partner` excel files aren't included in the `MANIFEST.in` file][2].

[1]:https://github.com/PSLmodels/B-Tax/tree/master/btax/data/raw_data/soi/soi_partner
[2]:https://github.com/PSLmodels/B-Tax/blob/master/MANIFEST.in#L13

**Comment by jdebacker** [comment]
@hdoupe I think PR #232 will address this issue.  Let me double check that all other files are included and then I will merge and make a new package version.

**Comment by hdoupe** [comment]
Awesome, thanks @jdebacker.

**Comment by jdebacker** [comment]
@hdoupe Give it a try now with B-Tax version 0.2.8 and let me know if it works.  Thanks!

**Comment by hdoupe** [comment]
@jdebacker it looks like the xls file is there, but it's missing the `cps.csv.gz` file:

```
(pb_env) HDoupe-MacBook-Pro:PolicyBrain henrydoupe$ python btax_test.py 
/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/pandas/util/_decorators.py:178: FutureWarning: the 'skip_footer' keyword is deprecated, use 'skipfooter' instead
  return func(*args, **kwargs)
/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)
/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/pandas/io/excel.py:329: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  **kwds)
Dump asset_data.pkl
Loaded asset_data.pkl
Traceback (most recent call last):
  File "btax_test.py", line 5, in <module>
    result = runner_json_tables(inputs)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/btax/front_end_util.py", line 172, in runner_json_tables
    out = runner(test_run, start_year, iit_reform, **user_params)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/btax/execute.py", line 48, in runner
    run_btax(test_run, True, start_year, {}, **econ_params)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/btax/run_btax.py", line 110, in run_btax
    iit_reform, data, **user_params)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/btax/parameters.py", line 197, in get_params
    TAXDATA = pd.read_csv(TAXDATA_PATH, compression='gzip')
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 628, in pandas._libs.parsers.TextReader._setup_parser_source
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/btax/test_data/cps.csv.gz'
(pb_env) HDoupe-MacBook-Pro:PolicyBrain henrydoupe$ 
```

**Comment by jdebacker** [comment]
@hdoupe Unlike the other data sources that were missing (which surprised me since never an issue before and hadn't changed `MANIFEST.in` in a long time, there was never any reference to a folder with the `cps.csv.gz` files.  I guess I need to create one?  It seems like these would just be with Tax-Calculator that is a dependency, no?  

Note that, also unlike the other files missing from `MANIFEST.in`, I did not get an error when running B-Tax with this conda package on my machine:

```
(btax-dev) A02655JDEBACKER:run_examples jason.debacker$ conda list
# packages in environment at /anaconda3/envs/btax-dev:
#
# Name                    Version                   Build  Channel
...
btax                      0.2.8                    py36_0    pslmodels
...
(btax-dev) A02655JDEBACKER:run_examples jason.debacker$ python run_btax_example.py
WARNING: the Behavior class is deprecated and will be removed soon.
FUTURE: use the Behavioral-Responses behresp package OR
        use the Tax-Calculator quantity_response function.
You loaded data for 2014.
Your data include the following unused variables that will be ignored:
  filer
Tax-Calculator startup automatically extrapolated your data to 2014.
/anaconda3/envs/btax-dev/lib/python3.6/site-packages/pandas/util/_decorators.py:178: FutureWarning: the 'skip_footer' keyword is deprecated, use 'skipfooter' instead
  return func(*args, **kwargs)
/anaconda3/envs/btax-dev/lib/python3.6/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)
/anaconda3/envs/btax-dev/lib/python3.6/site-packages/pandas/io/excel.py:329: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  **kwds)
Dump asset_data.pkl
Loaded asset_data.pkl
WARNING: the Behavior class is deprecated and will be removed soon.
FUTURE: use the Behavioral-Responses behresp package OR
        use the Tax-Calculator quantity_response function.
You loaded data for 2014.
Your data include the following unused variables that will be ignored:
  filer
Tax-Calculator startup automatically extrapolated your data to 2014.
{'tau_nc': 0.19293920073099274, 'tau_div': 0.18824530341391923, 'tau_int': 0.3123930149661196, 'tau_scg': 0.29068556813477203, 'tau_lcg': 0.18837298576486794, 'tau_td': 0.21860396318335942, 'tau_h': 0.04376291336675393}
Loaded asset_data.pkl
WARNING: the Behavior class is deprecated and will be removed soon.
FUTURE: use the Behavioral-Responses behresp package OR
        use the Tax-Calculator quantity_response function.
You loaded data for 2014.
Your data include the following unused variables that will be ignored:
  filer
Tax-Calculator startup automatically extrapolated your data to 2014.
{'tau_nc': 0.25021384177046446, 'tau_div': 0.19638460869043492, 'tau_int': 0.34409032030241693, 'tau_scg': 0.3328792719988931, 'tau_lcg': 0.19953059023684766, 'tau_td': 0.2516468054276421, 'tau_h': 0.16613102816641817}
(btax-dev) A02655JDEBACKER:run_examples jason.debacker$
```

**Comment by hdoupe** [comment]
@jdebacker what happens when you run [`run_btax_example.py`](https://github.com/PSLmodels/B-Tax/blob/master/run_examples/run_btax_example.py) outside of the B-Tax directory? I just tried it and got the following error:

```
(pb_env) HDoupe-MacBook-Pro:PolicyBrain henrydoupe$ python -c "import btax; print(btax.__version__)"
0.2.8
(pb_env) HDoupe-MacBook-Pro:PolicyBrain henrydoupe$ cat run_btax_example.py 
"""
Runs B-Tax with TCJA as baseline and 2017 law as the reform.
------------------------------------------------------------------------
"""
# Import packages
from btax.run_btax import run_btax, run_btax_with_baseline_delta
from taxcalc import *

test_run = False  # flag for test run (for Travis CI)
start_year = 2018

# Note that TCJA is current law baseline in TC 0.16+
# Thus to compare TCJA to 2017 law, we'll use 2017 law as the reform
rec = Records.cps_constructor()
pol = Policy()
calc = Calculator(policy=pol, records=rec)
ref = calc.read_json_param_objects('2017_law.json', None)
iit_reform = ref['policy']

# Run B-Tax
run_btax_with_baseline_delta(test_run, start_year, iit_reform, data='cps',
                             btax_betr_corp=0.35, btax_depr_3yr_exp=50.,
                             btax_depr_5yr_exp=50.,
                             btax_depr_7yr_exp=50.,
                             btax_depr_10yr_exp=50.,
                             btax_depr_15yr_exp=50.,
                             btax_depr_20yr_exp=50.)
(pb_env) HDoupe-MacBook-Pro:PolicyBrain henrydoupe$ python run_btax_example.py 
/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/numba/errors.py:104: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
WARNING: the Behavior class is deprecated and will be removed soon.
FUTURE: use the Behavioral-Responses behresp package OR
        use the Tax-Calculator quantity_response function.
You loaded data for 2014.
Your data include the following unused variables that will be ignored:
  filer
Tax-Calculator startup automatically extrapolated your data to 2014.
Traceback (most recent call last):
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/taxcalc/utils.py", line 1794, in json_to_dict
    object_pairs_hook=collections.OrderedDict)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_btax_example.py", line 17, in <module>
    ref = calc.read_json_param_objects('2017_law.json', None)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/taxcalc/calculator.py", line 1176, in read_json_param_objects
    gdiff_resp_dict)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/taxcalc/calculator.py", line 1542, in _read_json_policy_reform_text
    raw_dict = json_to_dict(json_str)
  File "/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/taxcalc/utils.py", line 1809, in json_to_dict
    raise ValueError(msg)
ValueError: Text below contains invalid JSON:
Extra data: line 1 column 5 (char 4)
Above location of the first error may be approximate.
The invalid JSON text is between the lines:
XXXX----.----1----.----2----.----3----.----4----.----5----.----6----.----7
00012017_law.json
XXXX----.----1----.----2----.----3----.----4----.----5----.----6----.----7

(pb_env) HDoupe-MacBook-Pro:PolicyBrain henrydoupe$ python -c "import taxcalc; print(taxcalc.__version__)"
/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/numba/errors.py:104: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
0.24.0
(pb_env) HDoupe-MacBook-Pro:PolicyBrain henrydoupe$ 
```

**Comment by hdoupe** [comment]
@jdebacker said:
>  It seems like these would just be with Tax-Calculator that is a dependency, no?

Right, it should be with Tax-Calculator. I think you are passing the `cps.csv.gz` file that's in `btax/test_data` to Tax-Calculator right here in [`parameters.py`][1].

[1]: https://github.com/PSLmodels/B-Tax/blob/master/btax/parameters.py#L195-L207

**Comment by jdebacker** [comment]
@hdoupe, I get the same exception and also have Tax-Calc 0.24.0.  Did the format needed for the JSON files for TC change recently?

**Comment by hdoupe** [comment]
> @hdoupe, I get the same exception and also have Tax-Calc 0.24.0. Did the format needed for the JSON files for TC change recently?

Ah, it looks like I didn't have the `2017_law.json` file on my computer. I just copied the reform and everything ran ok: 

```
(pb_env) HDoupe-MacBook-Pro:PolicyBrain henrydoupe$ vim 2017_law.json 
(pb_env) HDoupe-MacBook-Pro:PolicyBrain henrydoupe$ python run_btax_example.py 
/Users/henrydoupe/anaconda3/envs/pb_env/lib/python3.6/site-packages/numba/errors.py:104: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
WARNING: the Behavior class is deprecated and will be removed soon.
FUTURE: use the Behavioral-Responses behresp package OR
        use the Tax-Calculator quantity_response function.
You loaded data for 2014.
Your data include the following unused variables that will be ignored:
  filer
Tax-Calculator startup automatically extrapolated your data to 2014.
Loaded asset_data.pkl
WARNING: the Behavior class is deprecated and will be removed soon.
FUTURE: use the Behavioral-Responses behresp package OR
        use the Tax-Calculator quantity_response function.
You loaded data for 2014.
Your data include the following unused variables that will be ignored:
  filer
Tax-Calculator startup automatically extrapolated your data to 2014.
{'tau_nc': 0.19293920073099274, 'tau_div': 0.18824530341391923, 'tau_int': 0.3123930149661196, 'tau_scg': 0.29068556813477203, 'tau_lcg': 0.18837298576486794, 'tau_td': 0.21860396318335942, 'tau_h': 0.04376291336675393}
Loaded asset_data.pkl
WARNING: the Behavior class is deprecated and will be removed soon.
FUTURE: use the Behavioral-Responses behresp package OR
        use the Tax-Calculator quantity_response function.
You loaded data for 2014.
Your data include the following unused variables that will be ignored:
  filer
Tax-Calculator startup automatically extrapolated your data to 2014.
{'tau_nc': 0.25021384177046446, 'tau_div': 0.19638460869043492, 'tau_int': 0.34409032030241693, 'tau_scg': 0.3328792719988931, 'tau_lcg': 0.19953059023684766, 'tau_td': 0.2516468054276421, 'tau_h': 0.16613102816641817}
```

It could be that PolicyBrain is calling B-Tax in an outdated way somehow. I'm able to run it just fine when I use the `run_btax_example.py` script.

**Comment by jdebacker** [comment]
Does your `btax_test.py` script have the `test` flag  = `True`?  That's probably the issue.  If that is true, it goes to look for the CPS files in a place they aren't installed with the package.  I'm making a quick fix to that now (it's a bit of code that is way outdated, from before the CPS was with TC and is just a check to be sure that the calculator will load).

**Comment by hdoupe** [comment]
No test flag was set, but I do have 0.2.8 running just fine right now. I didn't have the puf.csv file in the same directory as the example script, but it's there when I run B-Tax with the webapp. I'm all set. Sorry for bugging you so much about this!
